accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path(
        "change_password/", views.change_password, name="change_password"
    ),
    path("<int:user_pk>/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("delete/", views.delete, name="delete"),
    path("profileupdate/", views.profile_update, name="profile_update"),
] 
 

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.main, name="index"),
    path("<int:pk>/hotlist", views.hotlist, name="hotlist"),
    path("<int:pk>", views.hotdetail, name="hotdetail"),
    path("<int:pk>/hotcreate", views.hotcreate, name="hotcreate"),
    path("<int:pk>/reviewcreate", views.reviewcreate, name="reviewcreate"),
    path("<int:pk>/reviewdelete", views.reviewdelete, name="reviewdelete"),
    path("<int:pk>/hotupdate", views.hotupdate, name="hotupdate"),
    path("<str:slug>/hotlist", views.hotlist_theme, name="hotlist_theme"),
    path("<int:pk>/reviewupdate", views.reviewupdate, name="reviewupdate"),
    path("<int:pk>/like", views.like, name="like"),
    path('search', views.search, name='search'),
]

reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill


class Location(models.Model):
    location = models.CharField(max_length=80)
    country = models.BooleanField(default=True)


class ImageLocation(models.Model):
    location = models.ForeignKey(
        Location, on_delete=models.CASCADE, related_name="image"
    )
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )
    image_thumbnail = ImageSpecField(
        source="image",
        processors=[ResizeToFill(300, 300)],
        format="JPEG",
        options={"quality": 80},
    )


class HotPlace(models.Model):
    location = models.ForeignKey(
        Location, on_delete=models.CASCADE, related_name="hotplace"
    )
    hotplace = models.CharField(max_length=100)
    addr = models.CharField(max_length=80, blank=True, null=True)
    x = models.CharField(max_length=80, blank=True, null=True)
    y = models.CharField(max_length=80, blank=True, null=True)
    theme = models.CharField(max_length=80)
    country = models.CharField(max_length=50)
    content = models.TextField()
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_hotplaces"
    )


class ImageHotPlace(models.Model):
    hotplace = models.ForeignKey(
        HotPlace, on_delete=models.CASCADE, related_name="image"
    )
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )
    image_thumbnail = ImageSpecField(
        source="image",
        processors=[ResizeToFill(300, 300)],
        format="JPEG",
        options={"quality": 80},
    )


class Reviews(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hotplace = models.ForeignKey(HotPlace, on_delete=models.CASCADE, related_name='reviews')
    title = models.CharField(max_length=80)
    content = models.TextField()
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



class ImageReviews(models.Model):
    reviews = models.ForeignKey(Reviews, on_delete=models.CASCADE, related_name="image")
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )
    image_thumbnail = ImageSpecField(
        source="image",
        processors=[ResizeToFill(200, 200)],
        format="JPEG",
        options={"quality": 60},
    )

reviews/forms.py
from django import forms
from .models import Reviews, HotPlace, Location, ImageHotPlace, ImageReviews
from django.forms import ClearableFileInput

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['title', 'content', ]

class ReviewImageForm(forms.ModelForm):
    class Meta:
        model = ImageReviews
        fields = ['image', ]
        
class HotPlaceForm(forms.ModelForm):
    class Meta:
        model = HotPlace
        fields = ['hotplace', 'addr', 'theme', 'country', 'content', 'x', 'y', ]

class HotPlaceImageForm(forms.ModelForm):
    class Meta:
        model = ImageHotPlace
        fields = ['image', ]
        labels = {
            'image': '이미지'
        }
        widgets = {
            "image": ClearableFileInput(attrs={"multiple": True}),
        }

class HotUpdateForm(forms.ModelForm):
    class Meta:
        model = HotPlace
        fields = ['hotplace', 'theme', 'content', ]

class ReviewUpdateForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['title', 'content', 'grade', ]

reviews/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.db.models import Avg, Count, Max
from .models import Location, HotPlace, ImageHotPlace, Reviews, ImageReviews, Location
from .forms import (
    ReviewForm,
    HotPlaceForm,
    HotPlaceImageForm,
    ReviewImageForm,
    HotUpdateForm,
    ReviewUpdateForm,
)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.http import HttpResponseForbidden
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator

# Create your views here.


@login_required
def hotcreate(request, pk):
    location = get_object_or_404(Location, pk=pk)
    if request.method == "POST":
        image_form = HotPlaceImageForm(request.POST, request.FILES)
        form = HotPlaceForm(request.POST, request.FILES)
        images = request.FILES.getlist("image")
        if form.is_valid() and image_form.is_valid():
            hotplace = form.save(commit=False)
            hotplace.location = location
            if len(images):
                for image in images:
                    image_instance = ImageHotPlace(hotplace=hotplace, image=image)
                    hotplace.save()
                    image_instance.save()
            else:
                hotplace.save()
            return redirect("reviews:hotlist", pk)
        else:
            messages.warning(request, "모든 항목을 입력해 주세요.")
    else:
        form = HotPlaceForm()
        image_form = HotPlaceImageForm()
    context = {"image_form": image_form, "form": form, "location": location}
    return render(request, "reviews/hotcreate.html", context)


def main(request):
    domestics = Location.objects.filter(country=True)
    overseas = Location.objects.filter(country=False)
    themes = HotPlace.objects.values("theme").distinct()
    context = {
        "domestics": domestics,
        "overseas": overseas,
        "themes": themes,
    }
    return render(request, "reviews/index.html", context)


def hotlist(request, pk):
    location = get_object_or_404(Location, pk=pk)
    hotplaces = HotPlace.objects.filter(location_id=pk).annotate(star=Avg('reviews__grade')).annotate(latestdate=Max('reviews__updated_at'))
    paginator = Paginator(hotplaces, 6)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        "location": location,
        "hotplaces": posts,
    }
    return render(request, "reviews/hotlist.html", context)


def hotdetail(request, pk):
    hotplace = get_object_or_404(HotPlace, pk=pk)
    reviews = Reviews.objects.filter(hotplace=hotplace).order_by('-pk')
    avg = reviews.aggregate(Avg('grade'))
    images = ImageHotPlace.objects.filter(hotplace=hotplace)
    paginator = Paginator(reviews, 6)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        "hotplace": hotplace,
        "reviews": posts,
        "images": images,
        "avg":avg
    }
    return render(request, "reviews/hotdetail.html", context)


@login_required
def reviewcreate(request, pk):
    hotplace = get_object_or_404(HotPlace, pk=pk)
    print(request.POST)
    review_form = ReviewForm(request.POST, request.FILES)
    image_form = ReviewImageForm(request.POST, request.FILES)
    images = request.FILES.getlist("image")
    if review_form.is_valid() and image_form.is_valid():
        review = review_form.save(commit=False)
        review.hotplace = hotplace
        review.grade = request.POST['grade']
        review.user = request.user
        if len(images):
            for image in images:
                image_instance = ImageReviews(reviews=review, image=image)
                review.save()
                image_instance.save()
        else:
            review.save()
        return redirect("reviews:hotdetail", pk)
    else:
        review_form = ReviewForm()
        image_form = ReviewImageForm()
    context = {"review_form": review_form, "image_form": image_form}
    return render(request, "reviews/reviewcreate.html", context)


@login_required
def reviewdelete(request, pk):
    review = get_object_or_404(Reviews, pk=pk)
    if request.user == review.user:
        review.delete()
        return redirect("reviews:hotdetail", review.hotplace.pk)


@login_required
def hotupdate(request, pk):
    hotplace = get_object_or_404(HotPlace, pk=pk)
    if request.method == "POST":
        image_form = HotPlaceImageForm(request.POST, request.FILES, instance=hotplace)
        form = HotUpdateForm(request.POST, request.FILES, instance=hotplace)
        images = request.FILES.getlist("image")
        if form.is_valid() and image_form.is_valid():
            hotplace = form.save(commit=False)
            if len(images):
                for image in images:
                    image_instance = ImageHotPlace(hotplace=hotplace, image=image)
                    hotplace.save()
                    image_instance.save()
            else:
                hotplace.save()
            return redirect("reviews:hotdetail", pk)
    else:
        form = HotUpdateForm(instance=hotplace)
        image_form = HotPlaceImageForm(instance=hotplace)
    context = {
        "image_form": image_form,
        "form": form,
    }
    return render(request, "reviews/hotupdate.html", context)


def hotlist_theme(request, slug):
    if slug == "all":
        hotplaces = HotPlace.objects.all().annotate(star=Avg('reviews__grade')).annotate(latestdate=Max('reviews__updated_at'))
    else:
        hotplaces = HotPlace.objects.filter(theme=slug).annotate(star=Avg('reviews__grade')).annotate(latestdate=Max('reviews__updated_at'))
    context = {"hotplaces": hotplaces}
    return render(request, "reviews/hotlist_theme.html", context)

@login_required
def reviewupdate(request, pk):
    review = get_object_or_404(Reviews, pk=pk)
    review_form = ReviewForm(request.POST, request.FILES, instance=review)
    image_form = ReviewImageForm(request.POST, request.FILES, instance=review)
    images = request.FILES.getlist("image")
    if review_form.is_valid() and image_form.is_valid():
        review = review_form.save(commit=False)
        review.grade = request.POST['grade']
        if len(images):
            for image in images:
                image_instance = ImageReviews(reviews=review, image=image)
                review.save()
                image_instance.save()
        else:
            review.save()
        return redirect("reviews:hotdetail", review.hotplace.pk)
    else:
        review_form = ReviewForm(instance=review)
        image_form = ReviewImageForm(instance=review)
    context = {"review_form": review_form, "image_form": image_form}
    return render(request, "reviews/reviewcreate.html", context)

def search(request):
    search = request.GET.get("search")
    hotplaces = HotPlace.objects.filter(hotplace__icontains=search).annotate(star=Avg('reviews__grade')).annotate(latestdate=Max('reviews__updated_at'))
    context = {
        "hotplaces" : hotplaces,
    }
    return render(request, 'reviews/search.html', context)

@login_required
def like(request, pk):
    review = HotPlace.objects.get(pk=pk)
    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
        isLiked = False
    else:
        review.like_users.add(request.user)
        isLiked= True
    context = {
        'isLiked': isLiked,
        'likeCount': review.like_users.count()
    }
    return JsonResponse(context)

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">{{ hotplace.hotplace }} <span class="text-muted" style="font-size:12px;" >{{ images.count }}개의 사진이 있습니다.</span> </h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {% for img in images %}
            <div class="w-100">
                <img src="{{ img.image.url }}" alt="" class="mt-3 img-fluid">
            </div>
            {% endfor %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
    </div>
<div class="container d-flex justify-content-between">   
    <div class="m-3" style="width:700px">
        <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
        {% for img in images %}
            {% if forloop.first %}
                <img class="img-fluid" src="{{ img.image.url }}" alt="">
                {% endif%}
                {% endfor %}
        </a>
    </div>
    <div class="card m-3" style="width:50%;">
        <div class="card-body">
            <h3 class="card-title">{{ hotplace.hotplace }}</h3>
            <h6 class="card-subtitle mb-2 text-muted">{{ hotplace.country }} | {{ hotplace.location.location }} | {{ hotplace.theme }}</h6>
            <p class="card-text">{{ hotplace.content }}</p>
            <a href="https://map.naver.com/v5/search/{{ hotplace.addr }}" class="card-link" target='_blank'>길찾기: {{ hotplace.addr }}</a>
            <a href="{% url 'reviews:hotupdate' hotplace.pk %}" class="card-link" >정보 수정하기</a>
        </div>
    </div>
</div>

<div class="d-flex justify-content-center">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item mx-3" role="presentation">
            <button class="nav-link active" id="pills-domestic-tab" data-bs-toggle="pill" data-bs-target="#pills-domestic" type="button" role="tab" aria-controls="pills-domestic" aria-selected="true">위치</button>
        </li>
        <li class="nav-item mx-3" role="presentation">
            <button class="nav-link" id="pills-overseas-tab" data-bs-toggle="pill" data-bs-target="#pills-overseas" type="button" role="tab" aria-controls="pills-overseas" aria-selected="false">후기</button>
        </li>
    </ul>
</div>


<div class="container position-relative">
    <a href="{% url 'reviews:reviewcreate' hotplace.pk %}" class="btn btn-primary position-fixed" style="right:10%; bottom:20%; font-size:larger;">+ review</a>


<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-domestic" role="tabpanel" aria-labelledby="pills-domestic-tab" tabindex="0">
        <div class="d-flex justify-content-center container">
        <div class="m-3" id="staticMap" style="width:100%;height:600px;"></div>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-overseas" role="tabpanel" aria-labelledby="pills-overseas-tab" tabindex="0">
        <div class="d-flex justify-content-center">
        <div class="container row row-cols-1">
            <div class="row row-cols-3 py-5 px-3" style="">
                {% for review in reviews %}
                <div class="col">
                    <div class="card border-light mb-3">
                        {% for img in review.image.all %}
                        {% if forloop.first %}
                        <img src="{{ img.image.url }}" class="card-img-top" alt="...">
                        {% endif %}
                        {% endfor %}
                        <div class="card-body">
                            <h5 class="card-title">
                            {{review.title}}
                            </h5>
            
                            <h6 class="card-text">
                            {{review.content}}
                            </h6>
            
                            {{review.grade}}
                            {% if request.user == review.user %}
                                <div class="d-flex justify-content-end">
                                    <a href="{% url 'reviews:reviewupdate' review.pk %}" class="btn btn-warning">수정</a>
                                    <a href="{% url 'reviews:reviewdelete' review.pk %}" class="btn btn-danger">삭제</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=a296fe5c49ee5c07b18af90b459b38bb"></script>
<script>
var markerPosition  = new kakao.maps.LatLng(`{{ hotplace.y }}`, `{{ hotplace.x }}`); 

var marker = {
    position: markerPosition
};

var staticMapContainer  = document.getElementById('staticMap'),
    staticMapOption = { 
        center: new kakao.maps.LatLng(`{{ hotplace.y }}`, `{{ hotplace.x }}`),
        level: 3,
        marker: marker
    };    

// 이미지 지도를 생성합니다
var staticMap = new kakao.maps.StaticMap(staticMapContainer, staticMapOption);
</script>
{% endblock content %}

reviews/templates/reviews/hotcreate.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div name="box" class="container w-75 my-5">
    <h1></h1>
    
    <form name="mapform" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3"><label class="form-label" for="id_hotplace">명소 이름</label><input type="text" name="hotplace" maxlength="100" class="form-control" placeholder="명소 이름" required="" id="id_hotplace"></div>
        {% if location.country %}
        <div id="map" style="width:100%;height:400px;"></div>
        <label for="id_addr" class="form-label">주소</label>
        <div class="input-group mb-3">
            <input name="addr" maxlength="80" required="주소를 입력하고 지도를 클릭해 마커를 표시해 주세요!" type="text" class="form-control" placeholder="직접 입력하거나 지도를 클릭해 마커를 표시하세요." id="id_addr" aria-label="Recipient's username" aria-describedby="button-addon2">
            <button onclick="transform()" class="btn btn-primary" type="button" id="button-addon2">주소 확인</button>
        </div>
        <div class="mb-3"><label class="form-label" for="id_country">국가</label>
        <select name="country" class="form-select" aria-label="Default select example">
                <option selected>국내</option>
                <option>해외</option>
                </select>
        </div>
        {% else %}
        <div class="mb-3"><label class="form-label" for="id_country">국가</label>
            <select name="country" class="form-select" aria-label="Default select example">
                    <option>국내</option>
                    <option selected>해외</option>
            </select>
        </div>
        {% endif %}
        <div class="mb-3"><label class="form-label" for="id_theme" >테마</label>
            <select aria-label="Default select example" class="form-select mb-3" name="themeselect" onchange="theme_change()">
                <option value="9">직접입력</option>
                <option value="관광" selected>관광</option>
                <option value="테마파크">테마파크</option>
                <option value="액티비티">액티비티</option> 
                <option value="산">산</option>
                <option value="바다">바다</option>
                <option value="도시">도시</option> 
                <option value="문화재">문화재</option> 
            </select>
            <input required="" cols="40" rows="10" id="id_theme" class="form-control" type="hidden" name="theme" placeholder="테마를 직접입력하세요." value="관광">
        </div>

        <div class="mb-3"><label class="form-label" for="id_content">명소 설명</label><textarea name="content" cols="40" rows="10" class="form-control" placeholder="명소 설명" required="" id="id_content"></textarea></div>
        {% bootstrap_form image_form %}
        <input name="x" type="hidden" value="">
        <input name="y" type="hidden" value="">
        <button class="btn btn-primary" type="submit">submit</button>
    </form>
</div>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=a296fe5c49ee5c07b18af90b459b38bb&libraries=services"></script>
<script>
var enteraddress = document.querySelector('[name="addr"]')
enteraddress.addEventListener('keydown', function(event) {
  if (event.keyCode === 13) {
    document.getElementById('button-addon2').click();
  };
}, true);

var mapContainer = document.getElementById('map'),
    mapOption = { 
        center: new kakao.maps.LatLng(33.450701, 126.570667),
        level: 3
    };


var geocoder = new kakao.maps.services.Geocoder();
geocoder.addressSearch(`{{ location.location }}`, function(result, status) {
     if (status === kakao.maps.services.Status.OK) {
        var coords = new kakao.maps.LatLng(result[0].y, result[0].x);
        map.setCenter(coords);
    } 
});

var map = new kakao.maps.Map(mapContainer, mapOption);

var marker = new kakao.maps.Marker({ 
    position: map.getCenter()
}); 

marker.setMap(map);
kakao.maps.event.addListener(map, 'click', function(mouseEvent) {
function searchAddrFromCoords(coords, callback) {
    geocoder.coord2RegionCode(coords.getLng(), coords.getLat(), callback);         
}

function searchDetailAddrFromCoords(coords, callback) {
    geocoder.coord2Address(coords.getLng(), coords.getLat(), callback);
}
searchDetailAddrFromCoords(mouseEvent.latLng, function(result, status) {
        if (status === kakao.maps.services.Status.OK) {
            var detailAddr = !!result[0].road_address ? '<div>도로명주소 : ' + result[0].road_address.address_name + '</div>' : '';
            detailAddr += '<div>지번 주소 : ' + result[0].address.address_name + '</div>';
            
            var content = '<div class="bAddr">' +
                            '<span class="title">법정동 주소정보</span>' + 
                            detailAddr + 
                        '</div>';
            marker.setPosition(mouseEvent.latLng);
            marker.setMap(map);
            document.mapform.addr.value=result[0].road_address.address_name

        }   
    });
     
    var latlng = mouseEvent.latLng; 
    
    // 마커 위치를 클릭한 위치로 옮깁니다
    marker.setPosition(latlng);
    document.mapform.x.value=latlng['La']
    document.mapform.y.value=latlng['Ma']
    
});
function transform() {
    var geocoder = new kakao.maps.services.Geocoder();
    var address = document.mapform.addr.value
    geocoder.addressSearch(`${address}`, function(result, status) {
        if (status === kakao.maps.services.Status.OK) {
            var coords = new kakao.maps.LatLng(result[0].y, result[0].x);
        // 인포윈도우로 장소에 대한 설명을 표시합니다
        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
        map.setCenter(coords);
    } else {
        alert('정확한 주소를 입력해 주세요. \n( 지번 또는 도로명주소 포맷을 지원합니다. )')
    } 
});
}
function theme_change(){
if(document.mapform.themeselect.options[document.mapform.themeselect.selectedIndex].value == '9'){
 document.mapform.theme.type = "text"
 document.mapform.theme.value ="";
 document.mapform.theme.focus();
} else{
 document.mapform.theme.type = "hidden"
 document.mapform.theme.value = document.mapform.themeselect.options[document.mapform.themeselect.selectedIndex].value;
}
}
</script>
{% endblock %}

reviews/templates/reviews/hotlist_theme.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load humanize %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'reviews/css/style.css' %}">{% endblock css %}
{% block content %}
<div id="carouselExampleControls" class="carousel slide w-75 my-3 mx-auto" data-bs-ride="carousel">
    <div class="carousel-inner">
        <img src="https://picsum.photos/700/500" class="d-block w-100" alt="...">
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  
  <div class="d-flex justify-content-center mt-3 my-3" style="height: 35px;">
    <form class="d-flex" role="search" action=" {% url 'reviews:search' %}">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
          name="search">
      <button class="btn btn-outline-dark" type="submit">Search</button>
    </form>
    </div>
<div class="container position-relative">
  {% for hotplace in hotplaces %}
    <div class="row g-0 mt-3 border rounded">
      <div class="col-md-8">
        <div class="card-body m-3">
          <a href="{% url 'reviews:hotdetail' hotplace.pk %}" style="text-decoration:none; color:black;">
            <h6 class="card-title fw-bold">{{ hotplace.hotplace }}</h6>
          </a>
          <p class="card-text">{{ hotplace.theme }} | {{ hotplace.location.location }} | {{ hotplace.addr }}</p>
          <!-- star -->
          {% if hotplace.latestdate %}
          <label class="rating-label">평점: {{ hotplace.star|floatformat:2 }} 점
            <input
              class="rating"
              max="5"
              readonly
              step="0.01"
              style="--fill:gold;--value:{{ hotplace.star }}"
              type="range"
              value="{{ hotplace.star }}">
          </label>
          <p class="card-text">
            <small class="text-muted">최근 후기: {{ hotplace.latestdate|naturaltime }}</small>
            {% else %}
            <small class="text-muted">최근 후기: 아직 후기가 없어요!</small>
            {% endif %}
          </p>
          <a href="#" class="btn btn-info btn-sm">예약가능</a>

            {% if request.user.is_authenticated %}
                {% if request.user in hotplace.like_users.all %}
                  <i id="like-btn" data-hotplace-id="{{ hotplace.pk }}" class="bi bi-heart-fill" style="color:red; cursor: pointer;"></i>
                {% else %}
                  <i id="like-btn" data-hotplace-id="{{ hotplace.pk }}" class="bi bi-heart" style="color:red; cursor: pointer;"></i>
                {% endif %}
              <span id="like-count" >{{ hotplace.like_users.count }}</span>
              <i class="bi bi-chat"></i> {{ hotplace.reviews.count }}
            {% endif %}

        </div>
      </div>
      <div class="col-md-4">
        {% for img in hotplace.image.all %}
          {% if forloop.first %}
          <a href="{% url 'reviews:hotdetail' hotplace.pk %}" style="text-decoration:none; color:black;">
            <div class="position-relative">
              <img class="w-100 rounded-end" src="{{ img.image.url }}" alt="">
              
            </div>
          </a>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

reviews/templates/reviews/hotupdate.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_form image_form %}
    <button class="btn btn-primary" type="submit">OK</button>
</form>

{% endblock content %}