accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path(
        "change_password/", views.change_password, name="change_password"
    ),
    path("<int:user_pk>/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("delete/", views.delete, name="delete"),
    path("profileupdate/", views.profile_update, name="profile_update"),
] 
 

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[Thumbnail(60, 60)],
        format="JPEG",
        options={"quality": 90},
    )

    @property
    def full_name(self):
        return f"{self.last_name}{self.first_name}"


class Profile(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_pk"
    )
    image = ProcessedImageField(
        blank=True,
        processors=[Thumbnail(200, 300)],
        format="JPEG",
        options={"quality": 50},
    )

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile
from django import forms



class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "image",
        )

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignupForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.http import HttpResponseForbidden
from .forms import CustomUserChangeForm, ProfileForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def signup(request):
    if request.method == "POST":
        forms = SignupForm(request.POST, request.FILES)
        if forms.is_valid():
            forms.save()
            return redirect("reviews:index")
    else:
        forms = SignupForm()
    context = {
        "forms": forms,
    }
    return render(request, "accounts/signup.html", context)


def index(request):
    members = get_user_model().objects.all()
    return render(request, "accounts/index.html")


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm()
    context = {"forms": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:index")


@login_required
def update(request):
    if request.method == "POST":
        forms = CustomUserChangeForm(request.POST, instance=request.user)
        if forms.is_valid():
            forms.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        forms = CustomUserChangeForm(instance=request.user)
    context = {
        "forms": forms,
    }
    return render(request, "accounts/update.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        forms = PasswordChangeForm(request.user, request.POST)
        if forms.is_valid():
            forms.save()
            return redirect("accounts:detail")
    else:
        forms = PasswordChangeForm(request.user)
    context = {
        "forms": forms,
    }
    return render(request, "accounts/change_password.html", context)


def detail(request, user_pk):
    person = get_user_model()
    person = get_object_or_404(person, pk=user_pk)
    context = {
        "person": person,
    }
    return render(request, "accounts/detail.html", context)


@login_required
def follow(request, user_pk):
    person = get_user_model().objects.get(pk=user_pk)
    if person != request.user:
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
        return redirect("accounts:detail", user_pk)
    else:
        return HttpResponseForbidden()


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("accounts:login")


@login_required
def profile_update(request):
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = ProfileForm(instance=request.user)
    return render(
        request,
        "accounts/profile_update.html",
        {
            "form": form,
        },
    )

accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<form method="POST" action="{% url 'accounts:change_password' %}">
  {% csrf_token %}

<h1 class= mb-5>비밀번호 변경</h1>

{% bootstrap_form forms %}
{% bootstrap_button button_type="submit" button_class="btn-primary" content="변경완료" %}
<button type="button" class="btn btn-outline-dark" href= "{% url 'accounts:detail' request.user.pk %} ">돌아가기</button>
</form>

{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-4 p-3">
        {% if person.image %}
          <img src="{{ person.image.url }}" alt="">
        {% else %}
          <img src="https://dummyimage.com/300x200/deed11/e1ff00" alt="프사 대체">
        {% endif %}
      </div>
      <div class="col p-3">
        <div class="d-flex">
          <h2 class="fw-bold">{{ person }}
            <span class="fs-5 ms-3 fw-light">팔로잉 :
              {{ person.followings.count }}
              |
            </span><span class="fs-5 fw-light">팔로워 :
              {{ person.followers.count }}</span></h2>

          {% if request.user.is_authenticated %}
          {% if request.user.pk != person.pk %}
              {% if request.user in person.followers.all %}
              <p class="ms-5">
                  <form action="{% url 'accounts:follow' person.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="언팔로우" class="btn btn-outline-danger">
                  </form>
              </p>
              {% else %}
            <p class="ms-5">
              <form action="{% url 'accounts:follow' person.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="팔로우" class="btn btn-outline-primary">
              </form>
            </p>
              {% endif %}
          {% endif %}
          {% endif %}
        </div>
        <hr>
        <a class="fs-5 fw-light" href="{% url 'accounts:profile_update' %}">회원정보 수정
        </a>

      </div>
    </div>
  </div>

  <!-- Navagation -->
  <div class="card text-center">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link active" aria-current="true" href="#">Activity Feed</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">게시물</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">Photos</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <!-- 회원정보 -->
      <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
          <div class="card">

            <div class="card-body">
              <h5 class="card-title">회원정보</h5>
              <p align="left">이메일 :
                {{ person.email }}</p>
              <p align="left">가입일 :
                {{ person.date_joined }}</p>
              <p align="left">마지막 로그인 :
                {{ person.last_login }}</p>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">방명록</h5>
              <div class="align-bottom">
                <p align="left">Title :
                  {{ person.title }}</p>
                <p align="left">Content :
                  {{ person.content }}</p>
              </div>
            </div>
        </ul>
      </a>
    </li>
  </div>
</div>
</div>
</div>

</div>
</div>

{% endblock %}

accounts/templates/accounts/index.html
{% extends "base.html" %} 
{% load django_bootstrap5 %} 
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}

<div class="d-flex justify-content-center ">
  <div class="card text-center" style="width: 500px; height: 400px;">
    <div class="card-body">
      <p class="card-text">
        {% if user.is_authenticated %}
        {% else %}
          <p class="mt-5">회원이신가요?</p>
          <a class="btn btn-primary w-100" href="{%  url 'accounts:login' %}">로그인</a>
        {% endif %}
          <!--회원이 아닌 경우-->
            <p class="mt-5">아직 회원이 아니신가요?</p>
              <a class="btn btn-primary w-100 mb-5" href="{%  url 'accounts:index' %}"> 회원가입</a>
        </div>
    </div>
  </div>
</div>
  {% endblock content %}
</div>

accounts/templates/accounts/login.html
{% extends "base.html" %} {% load django_bootstrap5 %} {% bootstrap_css %} 
{%bootstrap_javascript %} {% block content %}

<h1 class="text-center">로그인</h1>

<div class="create border py-5">
  <p class="text-center">
    <img
      src="https://previews.123rf.com/images/putracetol/putracetol1701/putracetol170100472/70564142-nature-coffee-bean-icon-logo-design-element.jpg"
      width="140"
      height="120"
      alt=""
    />
  </p>
  <form
    action="{% url 'accounts:login' %}"
    method="POST"
    enctype="multipart/form-data"
  >
    {% csrf_token %} {% bootstrap_form forms %} {% bootstrap_button content="로그인" button_type="submit" button_class="btn-outline-primary w-100" %}
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<form action="" method="POST" enctype="multipart/form-data">
  <h1>회원정보 수정</h1>
  <div class="container">
    <div class="row">
      <div class="col-4 p-3">

      <div class="d-flex align-items-center">
        {% if request.user.image %}
        <img src="{{ request.user.image.url }}" alt="" style="width: 150px; height: 150px; border-radius: 50%" />
        {% else %}
        <img src="https://dummyimage.com/400/ccb3cc/fff"  alt="프사 대체">
        {% endif %}
        <p class = "fs-3 my-2 ms-5" > {{ user.username }}</p>
        
      </div>
    </div>
  </div>
{% csrf_token %} 
{% bootstrap_form form %}
<input type="submit" class="btn btn-outline-dark" value="수정">
<a href="{% url 'accounts:change_password' %}" class="btn btn-secondary">비밀번호 변경</a>
<a href="{% url 'accounts:delete' %}" class="btn btn-secondary">회원탈퇴</a>
<a href="{% url 'accounts:detail' user.pk %}" class="btn btn-secondary">돌아가기</a>
</form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form forms %}
    <input type="submit" class="btn btn-outline-primary" value="회원가입">
  </form>

{% endblock content %}