accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path(
        "change_password/", views.change_password, name="change_password"
    ),
    path("<int:user_pk>/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("delete/", views.delete, name="delete"),
    path("profileupdate/", views.profile_update, name="profile_update"),
] 
 

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.main, name="index"),
    path("<int:pk>/hotlist", views.hotlist, name="hotlist"),
    path("<int:pk>", views.hotdetail, name="hotdetail"),
    path("<int:pk>/hotcreate", views.hotcreate, name="hotcreate"),
    path("<int:pk>/reviewcreate", views.reviewcreate, name="reviewcreate"),
    path("<int:pk>/reviewdelete", views.reviewdelete, name="reviewdelete"),
    path("<int:pk>/hotupdate", views.hotupdate, name="hotupdate"),
    path("<str:slug>/hotlist", views.hotlist_theme, name="hotlist_theme"),
    path("<int:pk>/reviewupdate", views.reviewupdate, name="reviewupdate"),
    path("<int:pk>/like", views.like, name="like"),
    path('search', views.search, name='search'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load django_bootstrap5 %}
    {% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BeanTeam Project</title>
    {% bootstrap_css %}
    {% block css %}<link rel="stylesheet" href="{% static 'css/style.css' %}">{% endblock css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>
  <!-- Design -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
  <script defer="defer" src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">

  <style>
.mdl-mini-footer {
  position: fixed;
  left: 0;
  bottom: 0;
  height: 80px;
  width: 100%;
}
body {
    margin: 0;
    font-family: 'Noto Sans KR', sans-serif;
  }


  </style>
  <body>

    <!-- Nav -->
    <nav class="navbar navbar-expand-lg border-bottom py-2">
      <div class="container d-flex justify-content-between">
        <a class="navbar-brand " href="{% url 'reviews:index' %}"><img src="https://previews.123rf.com/images/putracetol/putracetol1701/putracetol170100472/70564142-nature-coffee-bean-icon-logo-design-element.jpg" width="140" height="120" alt=""></a>
        <div class="justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav mb-2 mb-lg-0 d-flex align-items-center">
            <nav class=" container navbar navbar-expand-lg border-bottom">
              <div class="container d-flex justify-content-end">
                {% if request.user.image %}
                  <img src="{{ request.user.image.url }}" alt="" style="width: 50px; height: 50px; border-radius: 50%" class="ms-3"/>
                {% else %}
                  <img src="https://dummyimage.com/400/ccb3cc/fff" style="width: 30px; height: 30px; border-radius: 50%" alt="프사 대체">
                {% endif %}
                {% if user.is_authenticated %}
                  <a class="navbar-brand fw-bold ms-3" href="{% url 'accounts:detail' user.pk %}">{{ request.user.username }}</a>
                {% else %}
                  <a class="navbar-brand fw-bold px-2" href="#">비회원</a>
                {% endif %}
                <span>님 안녕하세요</span>
                {% if request.user.is_authenticated %}
                  <li class=" nav-item ms-3">
                    <a class="nav-link" href="{% url 'accounts:profile_update' %}">
                      <button class=" btn btn-primary">회원정보 수정</button>
                    </a>
                  </li>
                  <li class=" nav-item ms-3">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                      <button class=" btn btn-primary">로그아웃</button>
                    </a>
                  </li>
                {% else %}
                  <a class="nav-link ms-3" href="{% url 'accounts:login' %}">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                      로그인
                    </button>
                  </a>
                </li>
                <li class="nav-item margin-right-5">
                  <a class="nav-link ms-3" href="{% url 'accounts:signup' %}">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                      회원가입
                    </button></a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </nav>

      <div class="container">
        {% block content %}{% endblock content %}
      </div>

      <!-- footer design -->
      <div style="height:80px"></div>
      <footer class="mdl-mini-footer" style="z-index:2;">
        <div class="mdl-mini-footer__left-section">
          <div class="mdl-logo">Cong Team</div>
          <ul class="mdl-mini-footer__link-list">
            <li>
              <a href="#">Help</a>
            </li>
            <li>
              <a href="#">Privacy & Terms</a>
            </li>
          </ul>
        </div>
      </footer>

      <!-- footer without design </footer> <div class="card"> <div class="card-body"> <footer class="footer row text-center"> <p class="foottext align-self-center">Copyright @ 2022 Cong Team. All rights reserved.</p> <p class="foottext align-self-center">Contact Cong Team for more information.</p> </footer> </div> </div> -->
      <!-- JavaScript Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
      <script></script>

    </body>

  </html>